name: ainaglam
description: "Ainaglam Chat App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Common
  http: ^1.2.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  flutter_dotenv: ^5.0.2
  flutter_emoji: ^2.1.0
  socket_io_client: ^2.0.0
  flutter_quill: ^10.5.3
  flutter_bloc: ^8.1.3
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  go_router: ^11.1.3
  package_info_plus: ^4.2.0
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.4
  google_sign_in: ^6.1.4  
  flutter_html: ^3.0.0-beta.2
  intl: ^0.19.0


  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.5
  hive_generator: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true
# The following section is specific to Flutter packages.
flutter:
  
  assets:
    - assets/images/splash.png
    - assets/images/home-cong.svg
    - assets/images/logo-mark.svg
    - assets/images/google-logo.png
    - assets/.env
    - assets/avatars/a.png
    - assets/avatars/b.png
    - assets/avatars/c.png
    - assets/avatars/d.png
    - assets/avatars/e.png
    - assets/avatars/f.png
    - assets/avatars/g.png
    - assets/avatars/h.png
    - assets/avatars/i.png
    - assets/avatars/j.png
    - assets/avatars/k.png
    - assets/avatars/l.png
    - assets/avatars/m.png
    - assets/avatars/n.png
    - assets/avatars/o.png
    - assets/avatars/p.png
    - assets/avatars/q.png
    - assets/avatars/r.png
    - assets/avatars/s.png
    - assets/avatars/t.png
    - assets/avatars/u.png
    - assets/avatars/v.png
    - assets/avatars/w.png
    - assets/avatars/x.png
    - assets/avatars/y.png
    - assets/avatars/z.png
    - assets/avatars/default.png
    - assets/avatars/communite.png
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
